version: "3"

volumes:
  static_volume:
  media_volume:

services:
  nginx:
    image: 581301175753.dkr.ecr.ap-southeast-2.amazonaws.com/carbon_neutral_prod:nginx-1.0.0
    build: ./compose/prod/nginx
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    ports:
      - "80:80"
    depends_on:
      - backend

  backend: &backend
    image: 581301175753.dkr.ecr.ap-southeast-2.amazonaws.com/carbon_neutral_prod:django-1.0.0
    build:
      context: .
      dockerfile: ./compose/prod/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - redis
    command: /app/start
    env_file:
      - .env

  redis:
    image: redis

  celery: &celery
    <<: *backend
    image: 581301175753.dkr.ecr.ap-southeast-2.amazonaws.com/carbon_neutral_prod:celery-1.0.0
    ports: [ ]
    command: /app/start-celery

  celery_beat:
    <<: *celery
    image: 581301175753.dkr.ecr.ap-southeast-2.amazonaws.com/carbon_neutral_prod:celery-beat-1.0.0
    command: /app/start-celery-beat